In [15]:
import keras

In [16]:
! pip install Flask

^C



[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
! pip install --upgrade tensorflow
! pip install numpy pillow scikit-learn



[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
print(tf.__version__)


2.17.0


In [3]:
! pip install tensorflow==2.10.0
! pip install keras==2.10.0


ERROR: Could not find a version that satisfies the requirement tensorflow==2.10.0 (from versions: 2.16.0rc0, 2.16.1, 2.16.2, 2.17.0rc0, 2.17.0rc1, 2.17.0)
ERROR: No matching distribution found for tensorflow==2.10.0

[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


  Obtaining dependency information for keras==2.10.0 from https://files.pythonhosted.org/packages/f9/4d/dc255a437c9616b155e5bd55e325e092b7cdcb4652361d733ae051d40853/keras-2.10.0-py2.py3-none-any.whl.metadata
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
    --------------------------------------- 0.0/1.7 MB 187.9 kB/s eta 0:00:09
    --------------------------------------- 0.0/1.7 MB 178.6 kB/s eta 0:00:10
   - -------------------------------------- 0.1/1.7 MB 262.6 kB/s eta 0:00:07
   -- ------------------------------------- 0.1/1.7 MB 379.3 kB/s eta 0:00:05
   ---- ----------------------------------- 0.2/1.7 MB 541.9 kB/s eta 0:00:03
   ------ --------------------------------- 0.3/1.7 MB 630.2 kB/s eta 0:00:03
   ------- -------------------------------- 0.3/1.7 MB 678.1 kB/s eta 0:00:03
   -------- ------------------------------- 0.4/1.7 MB 716.8 kB/s eta 0:00:02
   --------- -----------------

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow-intel 2.17.0 requires keras>=3.2.0, but you have keras 2.10.0 which is incompatible.

[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [17]:
! pip install tifffile


[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import tifffile as tiff
! pip install keras==2.10.0       # Or the latest compatible version


ERROR: Invalid requirement: '#'

[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
! pip install tensorflow==2.10.0  # Or the latest compatible version
! pip install keras==2.10.0       # Or the latest compatible version
! pip install --upgrade segmentation-models
! pip install git+https://github.com/qubvel/segmentation_models


ERROR: Invalid requirement: '#'

[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: Invalid requirement: '#'

[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


  Obtaining dependency information for segmentation-models from https://files.pythonhosted.org/packages/da/b9/4a183518c21689a56b834eaaa45cad242d9ec09a4360b5b10139f23c63f4/segmentation_models-1.0.1-py3-none-any.whl.metadata
  Using cached segmentation_models-1.0.1-py3-none-any.whl.metadata (938 bytes)
  Obtaining dependency information for image-classifiers==1.0.0 from https://files.pythonhosted.org/packages/81/98/6f84720e299a4942ab80df5f76ab97b7828b24d1de5e9b2cbbe6073228b7/image_classifiers-1.0.0-py3-none-any.whl.metadata
  Using cached image_classifiers-1.0.0-py3-none-any.whl.metadata (8.6 kB)
  Obtaining dependency information for efficientnet==1.0.0 from https://files.pythonhosted.org/packages/97/82/f3ae07316f0461417dc54affab6e86ab188a5a22f33176d35271628b96e0/efficientnet-1.0.0-py3-none-any.whl.metadata
  Using cached efficientnet-1.0.0-py3-none-any.whl.metadata (6.1 kB)
Using cached segmentation_models-1.0.1-py3-none-any.whl (33 kB)
Using cached efficientnet-1.0.0-py3-none-any.whl 


[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


  Cloning https://github.com/qubvel/segmentation_models to c:\users\zedan net\appdata\local\temp\pip-req-build-6huhxur9
  Resolved https://github.com/qubvel/segmentation_models to commit 5d24bbfb28af6134e25e2c0b79e7727f6c0491d0
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Obtaining dependency information for efficientnet==1.1.1 from https://files.pythonhosted.org/packages/53/97/84f88e581d6ac86dcf1ab347c497c4c568c38784e3a2bd659b96912ab793/efficientnet-1.1.1-py3-none-any.whl.metadata
  Using cached efficientnet-1.1.1-py3-none-any.whl.metadata (6.4 kB)
Using cached efficientnet-1.1.1-py3-none-any.whl (18 kB)
  Attempting uninstall: efficientnet
    Found existing installation: efficientnet 1.0.0
    Uninstalling efficientnet-1.0.0:
      Successfully uninstalled efficientnet-1.0.0


  Running command git clone --filter=blob:none --quiet https://github.com/qubvel/segmentation_models 'C:\Users\Zedan Net\AppData\Local\Temp\pip-req-build-6huhxur9'
  Running command git submodule update --init --recursive -q
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
segmentation-models 1.0.1 requires efficientnet==1.0.0, but you have efficientnet 1.1.1 which is incompatible.

[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [7]:
! pip install -U segmentation-models==0.2.1
! pip install --upgrade tensorflow


  Obtaining dependency information for segmentation-models==0.2.1 from https://files.pythonhosted.org/packages/10/bf/253c8834014a834cacf2384c72872167fb30ccae7a56c6ce46285b03245c/segmentation_models-0.2.1-py2.py3-none-any.whl.metadata
  Using cached segmentation_models-0.2.1-py2.py3-none-any.whl.metadata (841 bytes)
  Obtaining dependency information for image-classifiers==0.2.0 from https://files.pythonhosted.org/packages/de/32/a1e74e03f74506d1e4b46bb2732ca5a7b18ac52a36b5e3547e63537ce74c/image_classifiers-0.2.0-py2.py3-none-any.whl.metadata
  Using cached image_classifiers-0.2.0-py2.py3-none-any.whl.metadata (8.3 kB)
Using cached segmentation_models-0.2.1-py2.py3-none-any.whl (44 kB)
Using cached image_classifiers-0.2.0-py2.py3-none-any.whl (76 kB)
  Attempting uninstall: image-classifiers
    Found existing installation: image-classifiers 1.0.0
    Uninstalling image-classifiers-1.0.0:
      Successfully uninstalled image-classifiers-1.0.0
  Attempting uninstall: segmentation-models
 


[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


  Obtaining dependency information for keras>=3.2.0 from https://files.pythonhosted.org/packages/a3/a4/101f0f3c0b057ce150af0e8493ab7fc10b98b066b7bd81ab01e96038a268/keras-3.5.0-py3-none-any.whl.metadata
  Using cached keras-3.5.0-py3-none-any.whl.metadata (5.8 kB)
Using cached keras-3.5.0-py3-none-any.whl (1.1 MB)
  Attempting uninstall: keras
    Found existing installation: keras 2.10.0
    Uninstalling keras-2.10.0:
      Successfully uninstalled keras-2.10.0



[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


----


In [1]:
import tifffile as tiff
import numpy as np
import tensorflow as tf
import segmentation_models as sm
import numpy as np
from PIL import Image
from sklearn.metrics import accuracy_score, jaccard_score, f1_score
from flask import Flask, request, render_template, redirect, url_for, send_file
import numpy as np
from PIL import Image
import tensorflow as tf
import os
import segmentation_models as sm

Segmentation Models: using `keras` framework.


---

In [13]:
sm.set_framework('tf.keras')  # Choose TensorFlow Keras as the backend

# Define constants
BACKBONE = 'resnet34'
INPUT_SHAPE = (128, 128, 12)  # Adjust as needed
CLASSES = 1  # Binary segmentation

# Load the saved U-Net model
model = tf.keras.models.load_model('unet_dice_model.h5', compile=False)
# print(model)

app = Flask(__name__)
UPLOAD_FOLDER = 'static/uploads/'
app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER

def min_max_scaling(x):
    return (x - np.min(x)) / (np.max(x) - np.min(x))

def preprocess_image(image_path):
    preprocess_input = sm.get_preprocessing(BACKBONE)

    # Load and preprocess the image
    img = tiff.imread(image_path)
    img = preprocess_input(img)

    img = tf.image.resize(img, (128, 128))  
    img = min_max_scaling(img)                      
    img = np.expand_dims(img, axis=0)      # Add batch dimension

    return img

# Postprocess segmentation map
def postprocess_output(output):
    output = np.squeeze(output, axis=0)               # Remove batch dimension
    output = np.argmax(output, axis=-1)               # Get the most probable class per pixel
    print(output)

    output_img = Image.fromarray((output * 255).astype(np.uint8))  # Convert to an image
    return output_img

@app.route("/", methods=["GET", "POST"])
def upload_and_predict():
    if request.method == "POST":
        if 'file' not in request.files:
            return "No file uploaded", 400
        file = request.files['file']

        if file.filename == '':
            return "No file selected", 400

        file_path = os.path.join(app.config['UPLOAD_FOLDER'], file.filename)
        file.save(file_path)

        # Preprocess image
        img = preprocess_image(file_path)

        output = model.predict(img)
        # print("Here 3")
        # print(output)

        output_img = postprocess_output(output)

        output_img_path = os.path.join(app.config['UPLOAD_FOLDER'], "output.png")
        output_img.save(output_img_path)
        # print(output_img)

        return send_file(output_img_path, mimetype='image/png')

    return '''
    <!doctype html>
    <title>Upload Image</title>
    <h1>Upload an image to get segmentation</h1>
    <form method=post enctype=multipart/form-data>
      <input type=file name=file>
      <input type=submit value=Upload>
    </form>
    '''


if __name__ == "__main__":
    app.run(debug=True ,use_reloader=False)


 * Serving Flask app '__main__'
 * Debug mode: on


 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
127.0.0.1 - - [19/Sep/2024 22:41:16] "GET / HTTP/1.1" 200 -


1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step


127.0.0.1 - - [19/Sep/2024 22:41:27] "POST / HTTP/1.1" 200 -


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [14]:
# Load images
predicted = Image.open('static/uploads/output.png').convert('L')
true = Image.open('data/labels/1.png').convert('L')

# Convert images to numpy arrays
predicted_array = np.array(predicted)
true_array = np.array(true)

# Ensure the arrays are binary (0 and 1)
predicted_array = (predicted_array > 128).astype(int)  # Assuming a threshold of 128
true_array = (true_array > 128).astype(int)  # Assuming a threshold of 128

# Flatten arrays for metric calculations
y_true = true_array.flatten()
y_pred = predicted_array.flatten()

# Calculate accuracy
accuracy = accuracy_score(y_true, y_pred)



print(f'Accuracy: {accuracy:.4f}')



Accuracy: 1.0000
